/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TurnkeyRouteImport } from './routes/turnkey'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RfqRouteImport } from './routes/rfq'
import { Route as ReferralRouteImport } from './routes/referral'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as InspectionRouteImport } from './routes/inspection'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ComplaintsRouteImport } from './routes/complaints'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AiChatRouteImport } from './routes/ai-chat'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TurnkeyProjectsRouteImport } from './routes/turnkey.projects'
import { Route as TurnkeyNewRouteImport } from './routes/turnkey.new'
import { Route as TurnkeyIdRouteImport } from './routes/turnkey.$id'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'

const TurnkeyRoute = TurnkeyRouteImport.update({
  id: '/turnkey',
  path: '/turnkey',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RfqRoute = RfqRouteImport.update({
  id: '/rfq',
  path: '/rfq',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralRoute = ReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectionRoute = InspectionRouteImport.update({
  id: '/inspection',
  path: '/inspection',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsRoute = ComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiChatRoute = AiChatRouteImport.update({
  id: '/ai-chat',
  path: '/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TurnkeyProjectsRoute = TurnkeyProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => TurnkeyRoute,
} as any)
const TurnkeyNewRoute = TurnkeyNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TurnkeyRoute,
} as any)
const TurnkeyIdRoute = TurnkeyIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TurnkeyRoute,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OrdersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-chat': typeof AiChatRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/companies': typeof CompaniesRoute
  '/complaints': typeof ComplaintsRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/inspection': typeof InspectionRoute
  '/marketplace': typeof MarketplaceRoute
  '/orders': typeof OrdersRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/referral': typeof ReferralRoute
  '/rfq': typeof RfqRoute
  '/services': typeof ServicesRoute
  '/subscription': typeof SubscriptionRoute
  '/suppliers': typeof SuppliersRoute
  '/terms': typeof TermsRoute
  '/turnkey': typeof TurnkeyRouteWithChildren
  '/orders/$id': typeof OrdersIdRoute
  '/product/$id': typeof ProductIdRoute
  '/turnkey/$id': typeof TurnkeyIdRoute
  '/turnkey/new': typeof TurnkeyNewRoute
  '/turnkey/projects': typeof TurnkeyProjectsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-chat': typeof AiChatRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/companies': typeof CompaniesRoute
  '/complaints': typeof ComplaintsRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/inspection': typeof InspectionRoute
  '/marketplace': typeof MarketplaceRoute
  '/orders': typeof OrdersRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/referral': typeof ReferralRoute
  '/rfq': typeof RfqRoute
  '/services': typeof ServicesRoute
  '/subscription': typeof SubscriptionRoute
  '/suppliers': typeof SuppliersRoute
  '/terms': typeof TermsRoute
  '/turnkey': typeof TurnkeyRouteWithChildren
  '/orders/$id': typeof OrdersIdRoute
  '/product/$id': typeof ProductIdRoute
  '/turnkey/$id': typeof TurnkeyIdRoute
  '/turnkey/new': typeof TurnkeyNewRoute
  '/turnkey/projects': typeof TurnkeyProjectsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-chat': typeof AiChatRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/companies': typeof CompaniesRoute
  '/complaints': typeof ComplaintsRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/inspection': typeof InspectionRoute
  '/marketplace': typeof MarketplaceRoute
  '/orders': typeof OrdersRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/referral': typeof ReferralRoute
  '/rfq': typeof RfqRoute
  '/services': typeof ServicesRoute
  '/subscription': typeof SubscriptionRoute
  '/suppliers': typeof SuppliersRoute
  '/terms': typeof TermsRoute
  '/turnkey': typeof TurnkeyRouteWithChildren
  '/orders/$id': typeof OrdersIdRoute
  '/product/$id': typeof ProductIdRoute
  '/turnkey/$id': typeof TurnkeyIdRoute
  '/turnkey/new': typeof TurnkeyNewRoute
  '/turnkey/projects': typeof TurnkeyProjectsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-chat'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/companies'
    | '/complaints'
    | '/contact'
    | '/faq'
    | '/inspection'
    | '/marketplace'
    | '/orders'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/projects'
    | '/referral'
    | '/rfq'
    | '/services'
    | '/subscription'
    | '/suppliers'
    | '/terms'
    | '/turnkey'
    | '/orders/$id'
    | '/product/$id'
    | '/turnkey/$id'
    | '/turnkey/new'
    | '/turnkey/projects'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-chat'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/companies'
    | '/complaints'
    | '/contact'
    | '/faq'
    | '/inspection'
    | '/marketplace'
    | '/orders'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/projects'
    | '/referral'
    | '/rfq'
    | '/services'
    | '/subscription'
    | '/suppliers'
    | '/terms'
    | '/turnkey'
    | '/orders/$id'
    | '/product/$id'
    | '/turnkey/$id'
    | '/turnkey/new'
    | '/turnkey/projects'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-chat'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/companies'
    | '/complaints'
    | '/contact'
    | '/faq'
    | '/inspection'
    | '/marketplace'
    | '/orders'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/projects'
    | '/referral'
    | '/rfq'
    | '/services'
    | '/subscription'
    | '/suppliers'
    | '/terms'
    | '/turnkey'
    | '/orders/$id'
    | '/product/$id'
    | '/turnkey/$id'
    | '/turnkey/new'
    | '/turnkey/projects'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiChatRoute: typeof AiChatRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  CompaniesRoute: typeof CompaniesRoute
  ComplaintsRoute: typeof ComplaintsRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  InspectionRoute: typeof InspectionRoute
  MarketplaceRoute: typeof MarketplaceRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ProjectsRoute: typeof ProjectsRoute
  ReferralRoute: typeof ReferralRoute
  RfqRoute: typeof RfqRoute
  ServicesRoute: typeof ServicesRoute
  SubscriptionRoute: typeof SubscriptionRoute
  SuppliersRoute: typeof SuppliersRoute
  TermsRoute: typeof TermsRoute
  TurnkeyRoute: typeof TurnkeyRouteWithChildren
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/turnkey': {
      id: '/turnkey'
      path: '/turnkey'
      fullPath: '/turnkey'
      preLoaderRoute: typeof TurnkeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rfq': {
      id: '/rfq'
      path: '/rfq'
      fullPath: '/rfq'
      preLoaderRoute: typeof RfqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referral': {
      id: '/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof ReferralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspection': {
      id: '/inspection'
      path: '/inspection'
      fullPath: '/inspection'
      preLoaderRoute: typeof InspectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints': {
      id: '/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof ComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-chat': {
      id: '/ai-chat'
      path: '/ai-chat'
      fullPath: '/ai-chat'
      preLoaderRoute: typeof AiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/turnkey/projects': {
      id: '/turnkey/projects'
      path: '/projects'
      fullPath: '/turnkey/projects'
      preLoaderRoute: typeof TurnkeyProjectsRouteImport
      parentRoute: typeof TurnkeyRoute
    }
    '/turnkey/new': {
      id: '/turnkey/new'
      path: '/new'
      fullPath: '/turnkey/new'
      preLoaderRoute: typeof TurnkeyNewRouteImport
      parentRoute: typeof TurnkeyRoute
    }
    '/turnkey/$id': {
      id: '/turnkey/$id'
      path: '/$id'
      fullPath: '/turnkey/$id'
      preLoaderRoute: typeof TurnkeyIdRouteImport
      parentRoute: typeof TurnkeyRoute
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof OrdersRoute
    }
  }
}

interface OrdersRouteChildren {
  OrdersIdRoute: typeof OrdersIdRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersIdRoute: OrdersIdRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

interface TurnkeyRouteChildren {
  TurnkeyIdRoute: typeof TurnkeyIdRoute
  TurnkeyNewRoute: typeof TurnkeyNewRoute
  TurnkeyProjectsRoute: typeof TurnkeyProjectsRoute
}

const TurnkeyRouteChildren: TurnkeyRouteChildren = {
  TurnkeyIdRoute: TurnkeyIdRoute,
  TurnkeyNewRoute: TurnkeyNewRoute,
  TurnkeyProjectsRoute: TurnkeyProjectsRoute,
}

const TurnkeyRouteWithChildren =
  TurnkeyRoute._addFileChildren(TurnkeyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiChatRoute: AiChatRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  CompaniesRoute: CompaniesRoute,
  ComplaintsRoute: ComplaintsRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  InspectionRoute: InspectionRoute,
  MarketplaceRoute: MarketplaceRoute,
  OrdersRoute: OrdersRouteWithChildren,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ProjectsRoute: ProjectsRoute,
  ReferralRoute: ReferralRoute,
  RfqRoute: RfqRoute,
  ServicesRoute: ServicesRoute,
  SubscriptionRoute: SubscriptionRoute,
  SuppliersRoute: SuppliersRoute,
  TermsRoute: TermsRoute,
  TurnkeyRoute: TurnkeyRouteWithChildren,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
