/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TurnkeyRouteImport } from './routes/turnkey'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as InspectionRouteImport } from './routes/inspection'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ComplaintsRouteImport } from './routes/complaints'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AiChatRouteImport } from './routes/ai-chat'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TurnkeyNewRouteImport } from './routes/turnkey.new'
import { Route as ProductIdRouteImport } from './routes/product.$id'

const TurnkeyRoute = TurnkeyRouteImport.update({
  id: '/turnkey',
  path: '/turnkey',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectionRoute = InspectionRouteImport.update({
  id: '/inspection',
  path: '/inspection',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsRoute = ComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiChatRoute = AiChatRouteImport.update({
  id: '/ai-chat',
  path: '/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TurnkeyNewRoute = TurnkeyNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TurnkeyRoute,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-chat': typeof AiChatRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/companies': typeof CompaniesRoute
  '/complaints': typeof ComplaintsRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/inspection': typeof InspectionRoute
  '/marketplace': typeof MarketplaceRoute
  '/orders': typeof OrdersRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/services': typeof ServicesRoute
  '/subscription': typeof SubscriptionRoute
  '/terms': typeof TermsRoute
  '/turnkey': typeof TurnkeyRouteWithChildren
  '/product/$id': typeof ProductIdRoute
  '/turnkey/new': typeof TurnkeyNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-chat': typeof AiChatRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/companies': typeof CompaniesRoute
  '/complaints': typeof ComplaintsRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/inspection': typeof InspectionRoute
  '/marketplace': typeof MarketplaceRoute
  '/orders': typeof OrdersRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/services': typeof ServicesRoute
  '/subscription': typeof SubscriptionRoute
  '/terms': typeof TermsRoute
  '/turnkey': typeof TurnkeyRouteWithChildren
  '/product/$id': typeof ProductIdRoute
  '/turnkey/new': typeof TurnkeyNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-chat': typeof AiChatRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/companies': typeof CompaniesRoute
  '/complaints': typeof ComplaintsRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/inspection': typeof InspectionRoute
  '/marketplace': typeof MarketplaceRoute
  '/orders': typeof OrdersRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/services': typeof ServicesRoute
  '/subscription': typeof SubscriptionRoute
  '/terms': typeof TermsRoute
  '/turnkey': typeof TurnkeyRouteWithChildren
  '/product/$id': typeof ProductIdRoute
  '/turnkey/new': typeof TurnkeyNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-chat'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/companies'
    | '/complaints'
    | '/contact'
    | '/faq'
    | '/inspection'
    | '/marketplace'
    | '/orders'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/services'
    | '/subscription'
    | '/terms'
    | '/turnkey'
    | '/product/$id'
    | '/turnkey/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-chat'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/companies'
    | '/complaints'
    | '/contact'
    | '/faq'
    | '/inspection'
    | '/marketplace'
    | '/orders'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/services'
    | '/subscription'
    | '/terms'
    | '/turnkey'
    | '/product/$id'
    | '/turnkey/new'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-chat'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/companies'
    | '/complaints'
    | '/contact'
    | '/faq'
    | '/inspection'
    | '/marketplace'
    | '/orders'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/services'
    | '/subscription'
    | '/terms'
    | '/turnkey'
    | '/product/$id'
    | '/turnkey/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiChatRoute: typeof AiChatRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  CompaniesRoute: typeof CompaniesRoute
  ComplaintsRoute: typeof ComplaintsRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  InspectionRoute: typeof InspectionRoute
  MarketplaceRoute: typeof MarketplaceRoute
  OrdersRoute: typeof OrdersRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ServicesRoute: typeof ServicesRoute
  SubscriptionRoute: typeof SubscriptionRoute
  TermsRoute: typeof TermsRoute
  TurnkeyRoute: typeof TurnkeyRouteWithChildren
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/turnkey': {
      id: '/turnkey'
      path: '/turnkey'
      fullPath: '/turnkey'
      preLoaderRoute: typeof TurnkeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspection': {
      id: '/inspection'
      path: '/inspection'
      fullPath: '/inspection'
      preLoaderRoute: typeof InspectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints': {
      id: '/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof ComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-chat': {
      id: '/ai-chat'
      path: '/ai-chat'
      fullPath: '/ai-chat'
      preLoaderRoute: typeof AiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/turnkey/new': {
      id: '/turnkey/new'
      path: '/new'
      fullPath: '/turnkey/new'
      preLoaderRoute: typeof TurnkeyNewRouteImport
      parentRoute: typeof TurnkeyRoute
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TurnkeyRouteChildren {
  TurnkeyNewRoute: typeof TurnkeyNewRoute
}

const TurnkeyRouteChildren: TurnkeyRouteChildren = {
  TurnkeyNewRoute: TurnkeyNewRoute,
}

const TurnkeyRouteWithChildren =
  TurnkeyRoute._addFileChildren(TurnkeyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiChatRoute: AiChatRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  CompaniesRoute: CompaniesRoute,
  ComplaintsRoute: ComplaintsRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  InspectionRoute: InspectionRoute,
  MarketplaceRoute: MarketplaceRoute,
  OrdersRoute: OrdersRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ServicesRoute: ServicesRoute,
  SubscriptionRoute: SubscriptionRoute,
  TermsRoute: TermsRoute,
  TurnkeyRoute: TurnkeyRouteWithChildren,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
